### ISSUE TITLE
Multiple feature requests

### ISSUE THREAD

**Issue by snake-4** [matteocontrini/PlainHttp#4]
Can the following features be added?

- First one being the automatic decompression of Brotli.
- Second is the ability to set the underlying `IWebProxy` manually using a field of `HttpRequest` instead of having the library construct a new one from a URI so that it is possible to use different proxy classes that implement `IWebProxy` which is what some SOCKS libraries do.
- Third one is to have a way to set the `Version` field of the underlying `HttpRequestMessage`'s so that it is possible to specify the HTTP version to be used.
- And the last one is to have some sort of abstraction over `CookieContainer`. Ideally an isolation of cookies between different requests and a way to preserve cookies would be pretty good.

**Comment by matteocontrini** [comment]
Brotli decompression and choosing the HTTP version have been included in the v1.3.0 release:

https://github.com/matteocontrini/PlainHttp/releases/tag/v1.3.0

I'm going to close this issue since I prefer individual issues to be opened, one for reach request/report.
